# Generated by Django 5.1.1 on 2025-08-01 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_event_id_alter_event_event_id_eventattendees'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='max_capacity',
            field=models.IntegerField(default=10000),
        ),
    ]
