# Generated by Django 5.1.1 on 2025-08-01 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_event_max_capacity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventattendees',
            name='id',
        ),
        migrations.AlterField(
            model_name='event',
            name='event_id',
            field=models.CharField(editable=False, max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='eventattendees',
            name='attendee_id',
            field=models.CharField(editable=False, max_length=50, primary_key=True, serialize=False),
        ),
    ]
